pie showData title Read-heavy (weights from profile definition)
    "ORG_CHART SP" : 30
    "DEPT_BUDGET SP" : 25
    "MAIL_LABEL SP" : 15
    "GET_EMP_PROJ SP" : 10
    "SUB_TOT_BUDGET SP" : 10
    "SELECT join" : 5
    "UPDATE budget" : 5
